name = "frijal"
compatibility_date = "2025-10-16"

pages_build_output_dir = "./"

[build]
  upload.exclude = [
    ".git/*",
    ".github/*",
    ".gitignore",
    ".wranglerignore",
    "wrangler.toml",
    "node_modules/*",
    "package.json",
    "package-lock.json",
    ".nojekyll",
    "README.md",
    "LICENSE",
    "artikelx/*",
    "mini/*",
    "sementara/*"
  ]
