name: Remove Custom Text Dual Mode 🤖 ChatGPT

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Teks/Tag yang ingin dihapus (contoh: <h3>ArtikelTerkait</h3> atau | frijal.github.io)'
        required: true
        default: '<h3>Artikel Terkait</h3>'
      folder:
        description: 'Folder target tempat file .html berada'
        required: true
        default: 'artikel'
      mode:
        description: 'Pilih mode eksekusi: commit langsung ke main atau buat Pull Request'
        required: true
        default: 'commit'
        type: choice
        options:
          - commit
          - pr

permissions:
  contents: write
  pull-requests: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_PAT || secrets.GITHUB_TOKEN }}

      - name: Remove target text safely
        shell: bash
        run: |
          set -e
          TARGET="${{ github.event.inputs.target }}"
          FOLDER="${{ github.event.inputs.folder }}"

          echo "✂️ Menghapus teks: $TARGET"
          echo "📂 Dari folder: $FOLDER"

          if [ -d "$FOLDER" ]; then
            # Escape sed-sensitive characters to avoid syntax errors
            ESCAPED_TARGET=$(printf '%s\n' "$TARGET" | sed 's/[\/&]/\\&/g')

            find "$FOLDER" -type f -name "*.html" -print0 | while IFS= read -r -d '' file; do
              echo "   ↳ Edit $file"
              sed -i "s#$ESCAPED_TARGET##g" "$file"
            done
          else
            echo "⚠️ Folder $FOLDER tidak ditemukan!"
            exit 1
          fi

      - name: Commit or Create PR with 🤖 ChatGPT Label
        shell: bash
        run: |
          set -e
          MODE="${{ github.event.inputs.mode }}"
          FOLDER="${{ github.event.inputs.folder }}"
          TARGET="${{ github.event.inputs.target }}"
          REPO="${{ github.repository }}"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "✅ Tidak ada perubahan untuk di-commit atau PR."
            exit 0
          fi

          if [ "$MODE" = "commit" ]; then
            echo "🚀 Mode: Commit langsung ke main"
            git add "$FOLDER"
            git commit -m "Remove text: '${TARGET}' from ${FOLDER}/*.html"
            git push origin main
            echo "✅ Perubahan berhasil dipush ke main."
          else
            echo "🚀 Mode: Pull Request"
            BRANCH="remove-text-$(date +%s)"
            git checkout -b "$BRANCH"
            git add "$FOLDER"
            git commit -m "Remove text: '${TARGET}' from ${FOLDER}/*.html"
            git push origin "$BRANCH"

            echo "📦 Membuat Pull Request..."
            gh pr create \
              --title "Remove text from ${FOLDER}/*.html" \
              --body "This PR removes the following text from HTML files in **${FOLDER}**:\n\n\`\`\`\n${TARGET}\n\`\`\`\n✅ Auto-generated by GitHub Actions (🤖 ChatGPT)." \
              --head "$BRANCH" \
              --base main \
              --label "🤖 ChatGPT"

            # Get and display the PR URL (fallback if unavailable)
            PR_URL=$(gh pr view --json url -q '.url' || echo "(lihat di tab Pull Requests)")
            echo "✅ Pull Request dibuat: $PR_URL"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT || secrets.GITHUB_TOKEN }}
