name: ☢️ Build and Generate Site Files

on:
  # ⬇️ Pemicu 1 Berjalan jika ada push ke main yang mengubah *.html di artikel/
  push:
    branches: ['main']
    paths:
      - 'artikel/*.html' # Pemicu ini diaktifkan kembali

  # ⬇️ Pemicu 2 Berjalan setelah Workflow 'Proses ArtikelX' selesai
  workflow_run:
    workflows: ["🔄 Proses ArtikelX"] # Pastikan NAMA workflow pertama SAMA PERSIS
    types:
      - completed # Hanya berjalan jika workflow pertama SELESAI
    branches: ['main'] # Hanya berjalan jika workflow pertama dijalankan di branch main

  # ⬇️ Pemicu 3 & 4: Manual dan Terjadwal (tetap ada)
  workflow_dispatch:  # Untuk menjalankan manual
  schedule:           # Untuk menjalankan terjadwal
    - cron: '0 20 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write

    steps:
      - name: '1. Checkout Repository'
        uses: actions/checkout@v4
        with:
          # Pastikan mengambil commit terbaru
          ref: ${{ github.ref }} 
          fetch-depth: 0 

      - name: '2. Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: '3. Install Dependencies'
        run: npm ci

      - name: '4. Generate artikel.json, sitemap.xml & RSS'
        run: |
          echo "📝 Generating site files..."
          node ext/generator.js
          node ext/rss.js
        env:
          RSS_LIMIT: 30

      - name: '5. Generate screenshots'
        run: |
          echo "📸 Generating screenshots (installing puppeteer)..."
          # Gunakan cache npm jika memungkinkan untuk puppeteer
          npm install puppeteer --no-save --cache .npm-cache --prefer-offline
          echo "Running screenshot script..."
          node ext/screenshot-puppeteer.js         
      
      - name: '6. Commit and Push All Generated Files'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --staged --quiet; then
            echo "✅ Tidak ada perubahan file yang di-generate, tidak perlu commit."
            # Jika dipicu oleh push, kita tidak ingin menghentikan workflow di sini
            # karena mungkin langkah deploy selanjutnya perlu berjalan meskipun file generated tidak berubah.
            # Jika dipicu oleh workflow_run/schedule/dispatch dan tidak ada perubahan, aman untuk keluar.
            if [[ "${{ github.event_name }}" != "push" ]]; then
              exit 0 
            else
              echo "Workflow dipicu oleh push, melanjutkan meskipun tidak ada file generated baru."
            fi
          fi

          # Hanya commit jika ada perubahan yang di-stage
          if ! git diff --staged --quiet; then
            echo "⏳ Perubahan ditemukan. Melakukan commit..."
            git commit -m "build: 🚀 img, html & json udah beres."

            echo "🔃 Melakukan sinkronisasi sebelum push..."
            git pull --rebase origin main || { echo "⚠️ Gagal pull --rebase, mencoba push biasa"; git pull origin main; }
            
            echo "🚀 Mendorong perubahan ke server..."
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: '7. Show Published Links & Summary'
        if: always() 
        run: |
          echo "--- Summary ---"
          echo "✅ File yang seharusnya di-generate:"
          echo "🔗 artikel.json: https://frijal.pages.dev/artikel.json"
          echo "🔗 sitemap.xml : https://frijal.pages.dev/sitemap.xml"
          echo "🔗 rss.xml     : https://frijal.pages.dev/rss.xml"
          echo "📊 Jumlah konten saat ini:"
          COUNTHTML=$(ls artikel/*.html 2>/dev/null | wc -l || echo 0)
          echo "➡️  $COUNTHTML artikel (*.html) di folder artikel/"
          COUNTWEBP=$(ls img/*.webp 2>/dev/null | wc -l || echo 0)
          echo "➡️  $COUNTWEBP cover (*.webp) di folder img/"
          # Tampilkan info pemicu
          echo "Triggered by: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          fi
