name: pindahkan file ke folder lainnya

on:
  workflow_dispatch:
    inputs:
      file_extension:
        description: 'Jenis file yang ingiin dipindahkan (contoh: mp3, jpg, txt)'
        required: true
        default: 'mp3'
      source_folder:
        description: 'Folder asal'
        required: true
        default: 'input'
      destination_folder:
        description: 'Folder tujuan'
        required: true
        default: 'output'

jobs:
  move-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Buat folder tujuan jika belum ada
        run: |
          mkdir -p "${{ github.event.inputs.destination_folder }}"

      - name: Pindahkan file sesuai ekstensi
        run: |
          shopt -s nullglob
          for file in "${{ github.event.inputs.source_folder }}"/*.${{ github.event.inputs.file_extension }}; do
            echo "Memindahkan $file ke ${{ github.event.inputs.destination_folder }}/"
            mv "$file" "${{ github.event.inputs.destination_folder }}/"
          done

      - name: Commit perubahan
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Move *.${{ github.event.inputs.file_extension }} from ${{ github.event.inputs.source_folder }} to ${{ github.event.inputs.destination_folder }}" || echo "Tidak ada perubahan"
          git push
