name: Ping Feeds & Sitemap

on:
  workflow_dispatch:    # Bisa dijalankan manual
  schedule:
    - cron: "0 6 * * *"    # Otomatis tiap hari jam 06:00 UTC (sekitar jam 14:00 WITA)

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Ping Feeds ke Ping-o-Matic
        run: |
          BASE_URL="https://frijal.pages.dev"
          BLOG_TITLE="Frijal Pages" # Ganti jika perlu
          FEEDS=(
            "feed-catatan-and-opini-sosial.xml"
            "feed-kuliner-gaya-hidup-and-kesehatan.xml"
            "feed-lainnya.xml"
            "feed-linux-and-open-source.xml"
            "feed-multimedia-and-editing.xml"
            "feed-sejarah-and-religi.xml"
            "feed-teknologi-web-ai-and-umum.xml"
            "rss.xml"
          )
          echo "--- Pinging Ping-o-Matic for ${#FEEDS[@]} feeds ---"
          for feed_file in "${FEEDS[@]}"; do
            FEED_URL="$BASE_URL/$feed_file"
            echo "Pinging: $FEED_URL"
            # Kirim request POST ke Ping-o-Matic
            # -s (silent), -o /dev/null (buang output), -X POST (metode), -d (data payload)
            curl -s -o /dev/null -X POST \
              --data-urlencode "title=$BLOG_TITLE" \
              --data-urlencode "blogurl=$BASE_URL/" \
              --data-urlencode "rssurl=$FEED_URL" \
              https://pingomatic.com/ping/
          done
          echo "--- Ping-o-Matic Pings Sent ---"

      - name: 📍 Ping Sitemap & Main RSS ke Google & Bing
        run: |
          BASE_URL="https://frijal.pages.dev"
          SITEMAP_URL="$BASE_URL/sitemap.xml"
          RSS_URL="$BASE_URL/rss.xml"        
          echo "--- Pinging Bing Yandex ---"
          echo "Pinging Sitemap: $SITEMAP_URL"
          curl -s "https://www.bing.com/ping?sitemap=$SITEMAP_URL"
          echo "Pinging RSS Feed: $RSS_URL"
          curl -s "https://www.bing.com/ping?sitemap=$RSS_URL"          
          echo "--- Google - Bing - Yandex Pings Sent ---"
